# Generated by Django 6.0.3 on 2026-04-04 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('units_taken', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('IN_FIELD', 'Out in Field'), ('SETTLED', 'Settled')], default='IN_FIELD', max_length=15)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issued_stock', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='disbursements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_returned_unsold', models.PositiveIntegerField(default=0)),
                ('units_damaged_melted', models.PositiveIntegerField(default=0)),
                ('cash_remitted', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('disbursement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='operations.dailydisbursement')),
                ('settled_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='processed_settlements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
