# Generated by Django 6.0.3 on 2026-04-07 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydisbursement',
            name='units_taken',
        ),
        migrations.AddField(
            model_name='dailydisbursement',
            name='carryover_units',
            field=models.IntegerField(default=0, help_text='Units brought back yesterday'),
        ),
        migrations.AddField(
            model_name='dailydisbursement',
            name='cart_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailydisbursement',
            name='current_area',
            field=models.CharField(default='Unknown', help_text='Where are they today? e.g., Lundi Park', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailydisbursement',
            name='ice_packs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailydisbursement',
            name='new_units',
            field=models.IntegerField(default=0, help_text='Fresh units taken today'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailydisbursement',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_disbursements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailydisbursement',
            name='rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailydisbursement',
            name='status',
            field=models.CharField(choices=[('Active', 'In Field'), ('Settled', 'Settled')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailysettlement',
            name='cash_remitted',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailysettlement',
            name='disbursement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.dailydisbursement'),
        ),
        migrations.AlterField(
            model_name='dailysettlement',
            name='settled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailysettlement',
            name='units_damaged_melted',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dailysettlement',
            name='units_returned_unsold',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Include country code, e.g., +26377...', max_length=20)),
                ('has_whatsapp', models.BooleanField(default=True)),
                ('security_deposit_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
