# Generated by Django 6.0.3 on 2026-04-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_remove_dailydisbursement_units_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('id_number', models.CharField(help_text='National ID Number', max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], max_length=50)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Hired - Account Created'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
    ]
