# Generated by Django 6.0.3 on 2026-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default='ad@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
